name: Pickup Pulse
favicon: null
layout_spectrum: 0.99679
typography_spectrum: 1
title: Pickup Industry Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dddddd'
    - '#100c09'
    - '#514131'
    - '#8d7e61'
  brandStrength: 0.375
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
