name: Pickup Pulse
favicon: null
layout_spectrum: 0.88934
typography_spectrum: 0.87103
title: Pickup Industry Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#382b3b'
    - '#979471'
    - '#dfc2ab'
    - '#862838'
  brandStrength: 0.1875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
