name: Pickup Pulse
favicon: null
layout_spectrum: 0.31459
typography_spectrum: 0.6801700259093195
title: Pickup Industry Blog
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dddddd'
    - '#100c09'
    - '#514131'
    - '#8d7e61'
  brandStrength: 0.5
  lightness: 0.958862187108025
  saturation: 0.5267074990551919
  rhythmicContrast: 0.5817657969892025
purpose: []
